name: heartbeat
on:
  schedule:
    - cron: '*/5 * * * *'   # alle 5 Minuten (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Runner time (UTC): $(date -u +'%Y-%m-%d %H:%M:%S')"
