name: Repo Keepalive (weekly)

on:
  schedule:
    # 1× pro Woche, So 03:00 UTC (Europa/Wien i. d. R. 04:00/05:00)
    - cron: "0 3 * * 0"
  workflow_dispatch: {}

permissions:
  issues: write
  contents: none

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Authenticate gh
        run: |
          set -euo pipefail
          echo "${GITHUB_TOKEN}" | gh auth login --with-token
          gh auth status -h github.com

      - name: Vars
        id: vars
        run: |
          echo "date=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$GITHUB_OUTPUT"

      - name: Install retry helper
        run: |
          set -euo pipefail
          cat > /usr/local/bin/retry <<'EOF'
          #!/usr/bin/env bash
          set -euo pipefail
          max="$1"; shift
          n=1; delay=2
          until "$@"; do
            if (( n >= max )); then
              echo "Command failed after ${n} attempts." >&2
              exit 1
            fi
            echo "Attempt ${n}/${max} failed. Retrying in ${delay}s..." >&2
            sleep "$delay"
            n=$((n+1)); delay=$((delay*2))
          done
          EOF
          chmod +x /usr/local/bin/retry

      - name: Find or create 'keepalive' issue
        id: issue
        run: |
          set -euo pipefail

          # try to find an open issue with title 'keepalive'
          issue_number="$(retry 3 gh issue list \
            --repo "$GITHUB_REPOSITORY" \
            --search 'keepalive in:title is:open' \
            --json number -q '.[0].number // ""')"

          if [ -z "$issue_number" ]; then
            # create issue (no --json supported here)
            retry 3 gh issue create \
              --repo "$GITHUB_REPOSITORY" \
              --title 'keepalive' \
              --body 'Automatisch erstellt, um Repository-Aktivität sicherzustellen.'

            # fetch the number afterwards
            issue_number="$(retry 3 gh issue list \
              --repo "$GITHUB_REPOSITORY" \
              --search 'keepalive in:title is:open' \
              --json number -q '.[0].number // ""')"
          fi

          if [ -z "$issue_number" ]; then
            echo "Could not determine issue number." >&2
            exit 1
          fi

          echo "issue_number=$issue_number" >> "$GITHUB_OUTPUT"

      - name: Post keepalive comment
        run: |
          set -euo pipefail
          body="Keepalive-Ping: ${{ steps.vars.outputs.date }} (run: ${GITHUB_RUN_ID})"
          retry 3 gh issue comment "${{ steps.issue.outputs.issue_number }}" \
            --repo "$GITHUB_REPOSITORY" \
            --body "$body"
